version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - ls
      - npm install -g serverless
      - npm install
      - cd serverless && npm install && cd -
  build:
    commands:
      - cd serverless && serverless deploy

cache:
  paths:
    - node_modules
    - serverless/node_modules
