service: test-form-submission

provider:
  name: aws
  region: us-east-2
  runtime: nodejs12.x

functions:
  contactFormSubmit:
    name: contact-form-submission-${self:provider.stage}
    handler: handler.contactFormSubmit
    events:
      - http:
          path: submit
          method: post
          cors:
            origins:
              - 'http://localhost:3000'
              - 'https://davidr.in'
    environment: 
      SES_ACCESS_KEY: ${ssm:/portfolio-ses-access-key~true}
      SES_SECRET: ${ssm:/portfolio-ses-secret-key~true}

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'