service: portfolio
frameworkVersion: '2'

provider:
  name: aws
  stage: ${opt:stage, 'develop'}
  region: us-east-2
  runtime: nodejs12.x
  memorySize: 128 # optional, in MB, default is 1024
  timeout: 30 # max timeout for API GW is 30 seconds

functions:
  contactFormSubmit:
    name: contact-form-submission-${self:provider.stage}
    handler: handler.contactFormSubmit
    events:
      - http:
          path: submit
          method: post
          cors:
            origins:
              - 'http://localhost:3000'
              - 'https://davidr.in'
    environment: 
      SES_ACCESS_KEY: ${ssm:/portfolio-ses-access-key~true}
      SES_SECRET: ${ssm:/portfolio-ses-secret-key~true}

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'